### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by jessecusack** [gunnarvoet/ctdproc#24]
Readthedocs appears to be out of date:
* `ctdproc.io.CTD(hexfile)` -> `ctdproc.io.CTDHex(hexfile)`
* Include step: `ctdproc.io.add_default_proc_params(cx)`

The notebook could be incorporated into the documentation.

**Comment by gunnarvoet** [comment]
I changed readthedocs to point to the latest version and this should be fixed now (I just tested by merging a pull request and it automatically rebuilt).

I'll create a separate issue for incorporating the notebook into the documentation.
