### ISSUE TITLE
Look over (and widen?) default processing parameter ranges  

### ISSUE THREAD

**Issue by oyvlun** [gunnarvoet/ctdproc#31]
Default conductivity bounds ``bounds_c = [2.5, 6]`` in ``ctd.io.add_default_proc_params`` are too restrictive for high-latitude upper ocean waters. 

- Suggest changing to ``[2, 6]`` or wider. No reason why this shouldn't work by default in cold fresh waters.
- Could perhaps be more explicit, i.e. raise a warning if a large fraction of data is thrown out due to this criteria? (It took me a while to figure out to figure out why half my profile was gone) 
- May want to look into the other parameters as well. Maybe we could include some test cases from very different ocean environments?

**Comment by gunnarvoet** [comment]
Great point - there is definitely no reason that this shouldn't work in all types of waters. Allowing wide ranges could be the default option. #5 proposes having a config file with processing options. That could be a good place for users to narrow down the ranges if they wish so. For the time being I'll make your suggested change to `[2, 6]`.

I definitely like your idea of raising a warning if many data points fall outside of allowed ranges. Feel free to submit a pull request if you'd like to see this.

As for test cases - yes, that would be awesome! This could also include somewhat difficult to process casts with, for example, heavy sea state and lots of CTD package motion...

**Comment by gunnarvoet** [comment]
I opened new issues #35 and #36 and will go ahead and close this.
